# Generated by Django 4.2.6 on 2023-10-16 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200, unique=True)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tunnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_symbol', models.CharField(max_length=20)),
                ('min_limit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_limit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('time_interval', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finances.user')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('datetime', models.DateTimeField()),
                ('suggestion', models.CharField(choices=[('B', 'Comprar'), ('S', 'Vender')], max_length=1)),
                ('tunnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finances.tunnel')),
            ],
        ),
    ]
