# Generated by Django 4.2.6 on 2023-10-12 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_personstock'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PersonStock',
            new_name='Tunnel',
        ),
    ]
