# Generated by Django 4.2.6 on 2023-10-13 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0005_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tunnel',
            name='max_limit',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tunnel',
            name='min_limit',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
