# Generated by Django 4.2.6 on 2023-10-13 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0006_alter_tunnel_max_limit_alter_tunnel_min_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
    ]
