# Generated by Django 4.2.6 on 2023-10-13 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0007_remove_notification_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='currentPrice',
            new_name='price',
        ),
    ]
